[package]
name = "howmanysmall/bytenet"
version = "0.4.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"dev",
	"docs",
	"CHANGELOG.md",
	"CONTRIBUTING.md",
	"dev.project.json",
	"mkdocs.yml",
	"package.json",
	"node_modules",
	"package-lock.json",
	"rokit.toml",
	"selene.toml",
	"style.md",
	"stylua.toml",
	"tsconfig.json",
	"bytenet.tar.gz",
]

[dependencies]
